/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AssetClass = "crypto" | "etfs" | "futures" | "mixed" | "options" | "stocks";

export type BrokerConnectionStatus = "connected" | "disconnected" | "error" | "pending" | "reconnecting";

export type BrokerProvider = "tradovate" | "webull";

export type CouponDurationUnit = "days" | "months";

export type CouponKind = "free_access" | "percent_discount";

export type CouponRedemptionStatus = "redeemed" | "released" | "reserved";

export type CueExitAlertStatus = "open" | "resolved";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MembershipStatus = "active" | "canceled" | "past_due" | "trial";

export type MembershipTier = "autopilot" | "copilot" | "scout";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaperOrderIntentStatus = "failed" | "submitted" | "submitting" | "uncertain";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export type WorkspaceKind = "crypto_24_7" | "day_trader" | "end_of_day" | "futures" | "long_term" | "morning_hunt" | "news_room" | "swing";

export interface AppSettings {
  key: string;
  updatedAt: Generated<Timestamp>;
  value: Json;
}

export interface BillingCheckouts {
  couponId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  stripeSessionId: string | null;
  tier: MembershipTier;
  url: string | null;
  userId: number;
}

export interface BillingEvents {
  id: string;
  receivedAt: Generated<Timestamp>;
}

export interface BrokerConnections {
  accessTokenExpiresAt: Timestamp | null;
  accountMask: string | null;
  accountType: string | null;
  connectedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  encryptedAccessToken: string | null;
  encryptedRefreshToken: string | null;
  externalAccountId: string | null;
  id: Generated<Int8>;
  isPaper: Generated<boolean>;
  lastSyncedAt: Timestamp | null;
  metadata: Generated<Json>;
  oauthAccessExpiresAt: Timestamp | null;
  oauthAccessTokenEncrypted: string | null;
  oauthIdentityId: string | null;
  oauthRefreshExpiresAt: Timestamp | null;
  oauthRefreshTokenEncrypted: string | null;
  oauthScope: string | null;
  oauthState: string | null;
  oauthStateExpiresAt: Timestamp | null;
  provider: BrokerProvider;
  refreshTokenExpiresAt: Timestamp | null;
  scopes: Generated<Json>;
  status: Generated<BrokerConnectionStatus>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface BrokerOauthStates {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<Int8>;
  provider: BrokerProvider;
  redirectAfter: Generated<string>;
  stateHash: string;
  usedAt: Timestamp | null;
  userId: number;
}

export interface CouponRedemptions {
  accessExpiresAt: Timestamp | null;
  checkoutSessionId: string | null;
  checkoutUrl: string | null;
  couponId: string;
  id: Generated<string>;
  redeemedAt: Timestamp | null;
  reservedAt: Generated<Timestamp>;
  status: CouponRedemptionStatus;
  userId: number;
}

export interface CueAuditLog {
  action: string;
  createdAt: Generated<Timestamp>;
  details: Generated<Json>;
  entityId: string | null;
  entityType: string | null;
  id: Generated<Int8>;
  userId: number | null;
}

export interface CueAutomationControls {
  autoPaperEnabled: Generated<boolean>;
  brainEnabled: Generated<boolean>;
  killSwitch: Generated<boolean>;
  maxAutoPositions: Generated<number>;
  perTradeBudget: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface CueDailyOutlooks {
  bias: string | null;
  createdAt: Generated<Timestamp>;
  headline: string | null;
  id: Generated<Int8>;
  marketMode: string | null;
  outlookType: string;
  plan: Generated<Json>;
  sessionDate: Timestamp;
  summary: string | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
  watchSymbols: Generated<Json>;
}

export interface CueExitAlerts {
  accountId: string;
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  lastIntentId: string | null;
  reason: string;
  resolvedAt: Timestamp | null;
  state: string;
  status: Generated<CueExitAlertStatus>;
  symbol: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface CueJournalExitFills {
  accountId: string;
  createdAt: Generated<Timestamp>;
  filledAt: Timestamp;
  fillId: string;
  id: Generated<Int8>;
  journalId: Int8;
  price: Numeric;
  priceSource: Generated<string>;
  qty: Numeric;
  userId: number;
}

export interface CueJournalProcessedFills {
  accountId: string;
  allocatedQty: Generated<Numeric>;
  fillId: string;
  processedAt: Generated<Timestamp>;
  qty: Numeric;
  symbol: string;
  userId: number;
}

export interface CueLearningProfiles {
  avgLoserR: Numeric | null;
  avgR: Numeric | null;
  avgWinnerR: Numeric | null;
  confidence: Generated<string>;
  expectancy: Numeric | null;
  id: Generated<Int8>;
  losses: Generated<number>;
  maxLosingStreak: Generated<number>;
  profitFactor: Numeric | null;
  setup: string;
  tradeCount: Generated<number>;
  updatedAt: Generated<Timestamp>;
  userId: number;
  winRate: Numeric | null;
  wins: Generated<number>;
}

export interface CueReliabilitySnapshots {
  checkedAt: Generated<Timestamp>;
  details: Generated<Json>;
  id: Generated<Int8>;
  latencyMs: number | null;
  message: string | null;
  service: string;
  status: string;
  userId: number | null;
}

export interface CueSkipTrainingObservations {
  action: string;
  confidence: Numeric;
  cueScore: Numeric | null;
  details: Generated<Json>;
  endPrice: Numeric | null;
  evaluatedAt: Timestamp | null;
  evaluationDueAt: Timestamp;
  id: Generated<Int8>;
  latestBarTime: Timestamp | null;
  maePercent: Numeric | null;
  marketMode: string;
  mfePercent: Numeric | null;
  observedAt: Generated<Timestamp>;
  observedPrice: Numeric;
  outcome: string | null;
  reason: string;
  setupGrade: string;
  setupScore: number;
  symbol: string;
  userId: number;
}

export interface CueTradeJournal {
  accountId: string;
  createdAt: Generated<Timestamp>;
  cueScore: Numeric | null;
  details: Generated<Json>;
  entryOrderId: string | null;
  entryPrice: Numeric | null;
  entryTime: Timestamp | null;
  exitOrderId: string | null;
  exitPrice: Numeric | null;
  exitTime: Timestamp | null;
  id: Generated<Int8>;
  mae: Numeric | null;
  mfe: Numeric | null;
  outcome: string | null;
  plannedRisk: Numeric | null;
  quantity: Numeric | null;
  realizedPnl: Numeric | null;
  realizedR: Numeric | null;
  setup: string | null;
  status: Generated<string>;
  stopPrice: Numeric | null;
  symbol: string;
  target1: Numeric | null;
  target2: Numeric | null;
  target3: Numeric | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface CueWorkerAccess {
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  paperExecutionEnabled: Generated<boolean>;
  tokenHash: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface CueWorkerState {
  completedAt: Timestamp | null;
  lastAction: Json | null;
  message: Generated<string>;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface FundamentalEvents {
  createdAt: Generated<Timestamp>;
  eventType: string;
  headline: string;
  id: Generated<Int8>;
  impactScore: number | null;
  publishedAt: Timestamp;
  rawPayload: Json | null;
  sentiment: string | null;
  sourceName: string;
  sourceUrl: string | null;
  summary: string | null;
  symbol: string;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface MembershipCoupons {
  active: Generated<boolean>;
  code: string;
  createdAt: Generated<Timestamp>;
  createdBy: number;
  durationUnit: CouponDurationUnit;
  durationValue: number;
  id: Generated<string>;
  kind: CouponKind;
  maxRedemptions: number;
  percentOff: number | null;
  redeemBy: Timestamp;
  tier: MembershipTier;
}

export interface OwnerSetup {
  claimedAt: Timestamp | null;
  email: string;
  expiresAt: Timestamp;
  tokenHash: string;
}

export interface PaperOrderIntents {
  accountId: string;
  brokerOrderId: string | null;
  childOrderIds: Json | null;
  clientOrderId: string;
  comboClientOrderId: string | null;
  context: Generated<Json>;
  createdAt: Generated<Timestamp>;
  error: string | null;
  id: Generated<Int8>;
  intentId: string;
  quantity: Numeric;
  requestHash: string;
  side: string;
  status: Generated<PaperOrderIntentStatus>;
  symbol: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface PaperOrders {
  accountId: string;
  brokerOrderId: string | null;
  clientOrderId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  instrumentId: string;
  limitPrice: Numeric | null;
  orderType: string;
  quantity: Numeric;
  rawResponse: Json | null;
  side: string;
  status: Generated<string>;
  symbol: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface PushSubscriptions {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  identity: string;
  subscription: Json;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface RiskProfiles {
  createdAt: Generated<Timestamp>;
  dayTradeFlatTimePt: Generated<string>;
  id: Generated<Int8>;
  longOnly: Generated<boolean>;
  maxDailyLoss: Generated<Numeric>;
  maxRiskPerTrade: Generated<Numeric>;
  maxTradesPerDay: Generated<number>;
  noChaseEnabled: Generated<boolean>;
  requireGreenConfirmation: Generated<boolean>;
  safeModeEnabled: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserMemberships {
  createdAt: Generated<Timestamp>;
  currentPeriodEndsAt: Timestamp | null;
  id: Generated<Int8>;
  status: Generated<MembershipStatus>;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  tier: Generated<MembershipTier>;
  trialEndsAt: Generated<Timestamp>;
  trialStartedAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserWorkspaces {
  config: Generated<Json>;
  createdAt: Generated<Timestamp>;
  defaultAssetClass: Generated<AssetClass>;
  id: Generated<Int8>;
  isDefault: Generated<boolean>;
  kind: WorkspaceKind;
  layoutMode: Generated<string>;
  name: string;
  quietMode: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface WatchlistItems {
  alertEnabled: Generated<boolean>;
  assetType: AssetClass;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  notes: string | null;
  sortOrder: Generated<number>;
  symbol: string;
  userId: number;
}

export interface WebullCredentials {
  appKeyEncrypted: string;
  appSecretEncrypted: string;
  createdAt: Generated<Timestamp>;
  userId: number;
  verifiedAt: Generated<Timestamp>;
}

export interface WebullMarketCache {
  expiresAt: Timestamp;
  payload: Json;
  requestKey: string;
}

export interface WebullMarketLimits {
  nextAt: Generated<Timestamp>;
  poolKey: string;
}

export interface DB {
  appSettings: AppSettings;
  billingCheckouts: BillingCheckouts;
  billingEvents: BillingEvents;
  brokerConnections: BrokerConnections;
  brokerOauthStates: BrokerOauthStates;
  couponRedemptions: CouponRedemptions;
  cueAuditLog: CueAuditLog;
  cueAutomationControls: CueAutomationControls;
  cueDailyOutlooks: CueDailyOutlooks;
  cueExitAlerts: CueExitAlerts;
  cueJournalExitFills: CueJournalExitFills;
  cueJournalProcessedFills: CueJournalProcessedFills;
  cueLearningProfiles: CueLearningProfiles;
  cueReliabilitySnapshots: CueReliabilitySnapshots;
  cueSkipTrainingObservations: CueSkipTrainingObservations;
  cueTradeJournal: CueTradeJournal;
  cueWorkerAccess: CueWorkerAccess;
  cueWorkerState: CueWorkerState;
  fundamentalEvents: FundamentalEvents;
  loginAttempts: LoginAttempts;
  membershipCoupons: MembershipCoupons;
  ownerSetup: OwnerSetup;
  paperOrderIntents: PaperOrderIntents;
  paperOrders: PaperOrders;
  pushSubscriptions: PushSubscriptions;
  riskProfiles: RiskProfiles;
  sessions: Sessions;
  userMemberships: UserMemberships;
  userPasswords: UserPasswords;
  users: Users;
  userWorkspaces: UserWorkspaces;
  watchlistItems: WatchlistItems;
  webullCredentials: WebullCredentials;
  webullMarketCache: WebullMarketCache;
  webullMarketLimits: WebullMarketLimits;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const MembershipTierArrayValues: [MembershipTier, ...MembershipTier[]] = ["autopilot","copilot","scout"];
export const MembershipStatusArrayValues: [MembershipStatus, ...MembershipStatus[]] = ["active","canceled","past_due","trial"];
export const BrokerProviderArrayValues: [BrokerProvider, ...BrokerProvider[]] = ["tradovate","webull"];
export const BrokerConnectionStatusArrayValues: [BrokerConnectionStatus, ...BrokerConnectionStatus[]] = ["connected","disconnected","error","pending","reconnecting"];
export const WorkspaceKindArrayValues: [WorkspaceKind, ...WorkspaceKind[]] = ["crypto_24_7","day_trader","end_of_day","futures","long_term","morning_hunt","news_room","swing"];
export const AssetClassArrayValues: [AssetClass, ...AssetClass[]] = ["crypto","etfs","futures","mixed","options","stocks"];
export const CouponKindArrayValues: [CouponKind, ...CouponKind[]] = ["free_access","percent_discount"];
export const CouponDurationUnitArrayValues: [CouponDurationUnit, ...CouponDurationUnit[]] = ["days","months"];
export const CouponRedemptionStatusArrayValues: [CouponRedemptionStatus, ...CouponRedemptionStatus[]] = ["redeemed","released","reserved"];
export const PaperOrderIntentStatusArrayValues: [PaperOrderIntentStatus, ...PaperOrderIntentStatus[]] = ["failed","submitted","submitting","uncertain"];
export const CueExitAlertStatusArrayValues: [CueExitAlertStatus, ...CueExitAlertStatus[]] = ["open","resolved"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.