import React,{useState}from "react";import {Link}from "react-router-dom";import {useQueryClient}from "@tanstack/react-query";
import {Button}from "../components/Button";import {Badge}from "../components/Badge";import {CouponManager}from "../components/CouponManager";import {WebullPanel}from "../components/WebullPanel";
import {useAdminOverview}from "../helpers/useAdminOverview";import {useAdminMembers}from "../helpers/useAdminMembers";import {useWebullAccount}from "../helpers/useWebullAccount";import {postBillingSetup}from "../endpoints/admin/billing-setup_POST.schema";
import styles from "./admin.module.css";
export default function AdminPage(){
 const [tab,setTab]=useState("Overview");const [accountId,setAccountId]=useState<string>();const [billingMessage,setBillingMessage]=useState("");const [billingBusy,setBillingBusy]=useState(false);
 const overview=useAdminOverview();const allowed=!!overview.data&&!overview.error;const members=useAdminMembers(allowed&&tab==="Members");const webull=useWebullAccount(allowed&&tab==="Webull","NVDA","5m",accountId);const q=useQueryClient();
 if(overview.isFetching&&!overview.data)return <div className={styles.loading}>Loading owner dashboard…</div>;
 if(!allowed)return <div className={styles.loading}><div className={styles.errorCard}><h1>Owner sign-in required</h1><p>{overview.error?.message||"Sign in with your owner account."}</p><Button asChild><Link to="/login">Sign in</Link></Button></div></div>;
 const d=overview.data!;
 return <div className={styles.shell}><header className={styles.topbar}><Link to="/" className={styles.brand}><span>///</span>Trade<strong>Cue</strong></Link><strong className={styles.consoleLabel}>OWNER DASHBOARD</strong><Badge variant="outline">AUTOPILOT OWNER ACCESS</Badge><Button asChild variant="outline"><Link to="/workstation">Open workstation</Link></Button></header>
 <div className={styles.layout}><aside className={styles.sidebar}>{["Overview","Coupons","Members","Webull","Billing","Audit trail"].map(t=><Button key={t} variant={tab===t?"secondary":"ghost"} onClick={()=>setTab(t)}>{t}</Button>)}<div className={styles.ownerNote}><small>OWNER ONLY</small><p>Member accounts and API keys are isolated. Coupon actions are recorded in the audit trail.</p></div></aside>
 <main className={styles.main}><div className={styles.pageHead}><div><span>TRADECUE OPERATIONS</span><h1>{tab}</h1><p>Manage access, connect accounts and review activity.</p></div><Button variant="outline" onClick={()=>q.invalidateQueries({queryKey:["admin"]})}>Refresh</Button></div>
 {tab==="Overview"&&<><section className={styles.kpis}><article><strong>{d.users}</strong><span>Registered members</span></article><article><strong>{d.memberships.autopilot}</strong><span>Autopilot memberships</span></article><article><strong>{d.memberships.copilot}</strong><span>Copilot memberships</span></article></section><section className={styles.panel}><h2>Your next steps</h2><p>Your owner account has Autopilot access. Your Webull paper account is available in the workstation.</p><div className={styles.tiers}><Button onClick={()=>setTab("Coupons")}>Generate membership coupons</Button><Button variant="outline" onClick={()=>setTab("Webull")}>View Webull accounts</Button><Button variant="outline" onClick={()=>setTab("Billing")}>Check billing setup</Button></div><p>Paper accounts and charts are connected. Automatic trading, live order execution, and the research feeds marked as previews are not active.</p></section></>}
 {tab==="Coupons"&&<CouponManager/>}
 {tab==="Members"&&<section className={styles.panel}><h2>Members & access</h2>{members.isFetching&&<p>Loading members…</p>}{members.error&&<p role="alert">{members.error.message}</p>}<div className={styles.audit}>{members.data?.members.map(m=><div key={m.id}><span>{m.displayName} · {m.email}</span><strong>{m.role==="admin"?"Owner · Autopilot":m.tier}</strong><small>{m.role==="admin"?"Permanent owner access":m.status}</small></div>)}</div></section>}
 {tab==="Webull"&&<><WebullPanel webull={webull} isOwner onAccount={setAccountId}/><section className={styles.panel}><h2>Other Webull users</h2><p>Members with approved Webull PaperTrade OpenAPI access can connect their own App Key and App Secret. Their accounts remain private.</p><p>A simple Webull sign-in flow for ordinary brokerage customers requires Webull Connect partner approval. That service is not active yet.</p><Button asChild variant="outline"><a href="https://www.webull.com/connect-api/info" target="_blank" rel="noreferrer">Webull partner application</a></Button><p>Callback: https://cuetrade.floot.app/_api/webull/callback</p></section></>}
 {tab==="Billing"&&<section className={styles.panel}><h2>Membership billing</h2><p>The connected Stripe account is currently being tested. Paid checkout is restricted to owner testing until live credentials and payment notifications are configured. Free access coupons work independently.</p><Button disabled={billingBusy} onClick={async()=>{setBillingBusy(true);try{const r=await postBillingSetup();setBillingMessage(r.live?"Live Stripe payment notifications configured.":"Stripe test payment notifications configured. Customers cannot be charged in this mode.");}catch(e){setBillingMessage(e instanceof Error?e.message:"Setup failed");}finally{setBillingBusy(false);}}}>{billingBusy?"Checking…":"Check and configure billing"}</Button><p role="status">{billingMessage}</p><Button asChild variant="outline"><Link to="/membership">Membership and checkout</Link></Button></section>}
 {tab==="Audit trail"&&<section className={styles.panel}><h2>Recent activity</h2><div className={styles.audit}>{d.recentAudit.length===0?<p>No activity yet.</p>:d.recentAudit.map(a=><div key={a.id}><span>{a.action}</span><strong>{a.entityType||"system"}</strong><time>{new Date(a.createdAt).toLocaleString()}</time></div>)}</div></section>}
 </main></div></div>;
}

