import React,{useState}from "react";import {Link,useSearchParams}from "react-router-dom";import {Button}from "../components/Button";import {Input}from "../components/Input";import {Form,FormItem,FormLabel,FormControl,FormMessage,useForm}from "../components/Form";import {schema}from "../endpoints/coupons/redeem_POST.schema";
import {useAuth}from "../helpers/useAuth";import {useEntitlements}from "../helpers/useEntitlements";import {useCoupons}from "../helpers/useCoupons";import {postCheckout}from "../endpoints/billing/checkout_POST.schema";import {postBillingPortal}from "../endpoints/billing/portal_POST.schema";import styles from "./membership.module.css";
export default function MembershipPage(){
 const {authState}=useAuth();const signed=authState.type==="authenticated";const e=useEntitlements(signed);const {redeem}=useCoupons();const f=useForm({schema,defaultValues:{code:""}});const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [params]=useSearchParams();
 const checkout=async(tier:"scout"|"copilot"|"autopilot",code?:string)=>{setBusy(true);setMessage("");try{const r=await postCheckout({tier,code});window.location.assign(r.url);}catch(err){setMessage(err instanceof Error?err.message:"Checkout failed");}finally{setBusy(false);}};
 if(!signed)return <main className={styles.page}><h1>Membership & coupons</h1><p>Sign in to redeem a code or manage membership.</p><Button asChild><Link to="/login">Sign in</Link></Button></main>;
 const discount=redeem.data?.kind==="percent_discount"?redeem.data:null;
 return <main className={styles.page}><header><Link to="/workstation">← Workstation</Link><strong>TradeCue</strong></header><h1>Membership & coupons</h1><p>Your access: <strong>{e.data?.membership.tier||"Loading…"}</strong>{authState.user.role==="admin"?" · Owner access":""}</p>
 {params.get("checkout")==="complete"&&<p>Payment confirmation is processed securely. Refresh your membership after confirmation.</p>}<Button variant="outline" onClick={()=>e.refetch()}>Refresh membership</Button>
 <section className={styles.panel}><h2>Have a coupon?</h2><Form {...f}><form className={styles.form} onSubmit={f.handleSubmit(v=>redeem.mutate(v))}><FormItem name="code"><FormLabel>Coupon code</FormLabel><FormControl><Input value={f.values.code} onChange={ev=>{f.setValues({code:ev.target.value});redeem.reset();}} placeholder="TC-…" autoComplete="off"/></FormControl><FormMessage/></FormItem><Button type="submit" disabled={redeem.isPending}>{redeem.isPending?"Checking…":"Apply code"}</Button></form></Form>
 {redeem.error&&<p role="alert">{redeem.error.message}</p>}
 {redeem.data?.kind==="free_access"&&<p role="status">Your {redeem.data.tier} access is active until {new Date(redeem.data.expiresAt).toLocaleString()}. No payment or automatic renewal.</p>}
 {discount&&<div><p>{discount.percentOff}% off {discount.tier} for {discount.months} months. Standard monthly pricing resumes afterward. This code is redeemed when payment succeeds.</p><Button disabled={busy} onClick={()=>checkout(discount.tier as "scout"|"copilot"|"autopilot",discount.code)}>Continue with discount</Button></div>}</section>
 <div className={styles.plans}>{([["scout",39],["copilot",129],["autopilot",249]]as const).map(([tier,price])=><section className={styles.panel} key={tier}><h2>{tier}</h2><strong>${price}/month</strong><p>Renews monthly until canceled. Review all charges in secure checkout.</p><Button disabled={busy} onClick={()=>checkout(tier)}>Choose {tier}</Button></section>)}</div>
 {message&&<p role="alert">{message}</p>}<Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await postBillingPortal();window.location.assign(r.url);}catch(err){setMessage(err instanceof Error?err.message:"Billing unavailable");}finally{setBusy(false);}}}>Manage or cancel subscription</Button></main>;
}
